version: '3.7'
services:
  limesurvey:
    build: './limesurvey/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: lime_data
        target: /var/www/html
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - type: volume
        source: lime_db
        target: /var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  lime_data:
  lime_db:
